### ISSUE TITLE
Can play take the seek elapsed time and song position number

### ISSUE THREAD

**Issue by 2devnull** [richiewebgate/volumio-mqtt#1]
Would like to know how to do this but with seek added since it appears the websocket api can do it and not the REST one:

From REST (where the N here is for song position in the queue):
```volumio.local/api/v1/commands/?cmd=play&N=2&<add seek>```

From websockets (where N is the elapsed time in seconds):
```Basic Playback Commands
**Play:** play
**Pause:** pause
**Stop:** stop
**Previous:** prev
**Next:** next
****Seek** seek N (N is the time in seconds that the playback will keep)**
**Random** setRandom({"value":true|false})
**repeat** setRepeat({"value":true|false})
```

**Comment by richiewebgate** [comment]
is your question how to use the seek command via mqtt? that's not implemented in my code yet. I have just implemented basic commands like play, pause, stop, volume etc.
let me know if you want to use the seek command in mqtt, then I will add it.

**Comment by 2devnull** [comment]
Yes, it would be nice if it is implemented. I had to do other workarounds but still not able to get seek type function to work.

**Comment by richiewebgate** [comment]
OK I have added an additional listener for the MQTT topic "{devicename}/set/seek" where you can specify the number of seconds to seek in the payload. A value of 90 will seek to 1:30 in the song.
