### ISSUE TITLE
Error on running (SyntaxError: Unexpected identifier)

### ISSUE THREAD

**Issue by anno73** [richiewebgate/volumio-mqtt#12]
Hi,

I installed volumio-mqtt today on rpi volumio image updated to the latest version 2.714, but did not get very far:

    root@volumio:/opt/node# git clone https://github.com/richiewebgate/volumio-mqtt.git
    Cloning into 'volumio-mqtt'...
    remote: Enumerating objects: 114, done.
    remote: Total 114 (delta 0), reused 0 (delta 0), pack-reused 114
    Receiving objects: 100% (114/114), 20.01 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (69/69), done.
    Checking connectivity... done.
    root@volumio:/opt/node# cd volumio-mqtt/
    root@volumio:/opt/node/volumio-mqtt# npm install
    npm notice created a lockfile as package-lock.json. You should commit this file.
    added 103 packages in 286.237s
    
    root@volumio:/opt/node/volumio-mqtt# node server.js
    /opt/node/volumio-mqtt/node_modules/xtend/immutable.js:1
    (function (exports, require, module, __filename, __dirname) { 5483711 horae_071~svn536.orig.tar.gz
                                                                          ^^^^^^^^^
    
    SyntaxError: Unexpected identifier
        at createScript (vm.js:80:10)
        at Object.runInThisContext (vm.js:139:10)
        at Module._compile (module.js:616:28)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/opt/node/volumio-mqtt/node_modules/mqtt/lib/store.js:6:13)
    
    root@volumio:/opt/node/volumio-mqtt# npm start
    
    > volumio-mqtt@1.0.0 start /opt/node/volumio-mqtt
    > node server.js
    
    /opt/node/volumio-mqtt/node_modules/xtend/immutable.js:1
    (function (exports, require, module, __filename, __dirname) { 5483711 horae_071~svn536.orig.tar.gz
                                                                          ^^^^^^^^^
    
    SyntaxError: Unexpected identifier
        at createScript (vm.js:80:10)
        at Object.runInThisContext (vm.js:139:10)
        at Module._compile (module.js:616:28)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/opt/node/volumio-mqtt/node_modules/mqtt/lib/store.js:6:13)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! volumio-mqtt@1.0.0 start: `node server.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the volumio-mqtt@1.0.0 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2020-03-10T20_23_27_942Z-debug.log

    root@volumio:/opt/node/volumio-mqtt# cat  /root/.npm/_logs/2020-03-10T20_23_27_942Z-debug.log
    0 info it worked if it ends with ok
    1 verbose cli [ '/bin/node', '/usr/local/bin/npm', 'start' ]
    2 info using npm@5.6.0
    3 info using node@v8.11.1
    4 verbose run-script [ 'prestart', 'start', 'poststart' ]
    5 info lifecycle volumio-mqtt@1.0.0~prestart: volumio-mqtt@1.0.0
    6 info lifecycle volumio-mqtt@1.0.0~start: volumio-mqtt@1.0.0
    7 verbose lifecycle volumio-mqtt@1.0.0~start: unsafe-perm in lifecycle true
    8 verbose lifecycle volumio-mqtt@1.0.0~start: PATH: /lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/node/volumio-mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    9 verbose lifecycle volumio-mqtt@1.0.0~start: CWD: /opt/node/volumio-mqtt
    10 silly lifecycle volumio-mqtt@1.0.0~start: Args: [ '-c', 'node server.js' ]
    11 silly lifecycle volumio-mqtt@1.0.0~start: Returned: code: 1  signal: null
    12 info lifecycle volumio-mqtt@1.0.0~start: Failed to exec start script
    13 verbose stack Error: volumio-mqtt@1.0.0 start: `node server.js`
    13 verbose stack Exit status 1
    13 verbose stack     at EventEmitter.<anonymous> (/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
    13 verbose stack     at emitTwo (events.js:126:13)
    13 verbose stack     at EventEmitter.emit (events.js:214:7)
    13 verbose stack     at ChildProcess.<anonymous> (/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    13 verbose stack     at emitTwo (events.js:126:13)
    13 verbose stack     at ChildProcess.emit (events.js:214:7)
    13 verbose stack     at maybeClose (internal/child_process.js:925:16)
    13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
    14 verbose pkgid volumio-mqtt@1.0.0
    15 verbose cwd /opt/node/volumio-mqtt
    16 verbose Linux 4.19.86+
    17 verbose argv "/bin/node" "/usr/local/bin/npm" "start"
    18 verbose node v8.11.1
    19 verbose npm  v5.6.0
    20 error code ELIFECYCLE
    21 error errno 1
    22 error volumio-mqtt@1.0.0 start: `node server.js`
    22 error Exit status 1
    23 error Failed at the volumio-mqtt@1.0.0 start script.
    23 error This is probably not a problem with npm. There is likely additional logging output above.
    24 verbose exit [ 1, true ]

Any help appreciated.

**Comment by richiewebgate** [comment]
hmm.. I just cloned a fresh copy, and it was running fine. 
did you copy config.js.sample to config.js and personalise it? and please double check the contents and syntax of config.js. maybe this caused the syntax error

**Comment by anno73** [comment]
After testing steps on cygwin and as volumio user on the volumio RPi with success, I deleted the initial root installation folder and re-did the above steps (incl config.js :-) as root. Now it works %-}
Playing with the syntax of config.js did not give me the error I got initially.
So, it now works :-D Thanks for this nice piece of software!

**Comment by richiewebgate** [comment]
cool, I'm glad to hear it's working now! thanks!!
