### ISSUE TITLE
Nothing happens after starting volumio-mqtt

### ISSUE THREAD

**Issue by jti989** [richiewebgate/volumio-mqtt#14]
Hi,

I have installed the npm package and it is running fine as far as I can see (pm2 list).
Unfortunately I am not able to control volumio, and the state of volumio isn't published to mqtt.

My config:
```
module.exports = {
    "volumio_host": 'http://localhost:80',
    "mqtt_devicename": "volumio",
    "mqttHost": "mqtt://192.168.2.240:1883",
    "mqtt_tvenabledtopic": "volumio/tv/status/wohnen/enabled",
    "mqtt_powerToggleAddr": "volumio/knx/set/4/1/7",
    "debug":false
}
```
Have tried port 80 (I access Volumio via browser on port 80) and port 3000 (default).
I am using mosquitto with tls, is that an issue here?

**Comment by richiewebgate** [comment]
hi there
stop the pm2 task, set "debug: true" and start volumio-mqtt manually from the command line (node server.js) to see if there is any output or error message.
cheers

**Comment by jti989** [comment]
Hi,
thanks for your quick reply.
I did what you said, but there is.. nothing. Not even a "server started" or something.
```

volumio@volumio:~$ pm2 stop 0
[PM2] Applying action stopProcessId on app [0](ids: 0)
[PM2] [volumio-mqtt](0) ✓
┌─────┬─────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name            │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼─────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ volumio-mqtt    │ default     │ 1.0.0   │ fork    │ 0        │ 0      │ 0    │ stopped   │ 0%       │ 0b       │ volumio  │ disabled │
└─────┴─────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
volumio@volumio:~$ cd volumio-mqtt/
volumio@volumio:~/volumio-mqtt$ node server.js 
^C
volumio@volumio:~/volumio-mqtt$ nano config.js
volumio@volumio:~/volumio-mqtt$ node server.js 

I waited for 5 minutes - still nothing.
```

**Comment by richiewebgate** [comment]
OK, later this day I will add more verbosity at startup for you, so you can see if both volumio and mqtt are connected.

**Comment by richiewebgate** [comment]
code is updated. please git pull and try again.
btw make sure your mqtt config line includes username and password like mqtt://user:pass@mqtthost:port
and use the unencrypted port.

manual startup should now immediately print something like:

$ node server.js 
[1/15/2021, 6:52:19 AM] Starting volumio-mqtt
[1/15/2021, 6:52:19 AM] Connecting to MQTT server..
[1/15/2021, 6:52:19 AM] Connecting to volumio player http://192.168.1.123:3000
[1/15/2021, 6:52:19 AM] Connected to MQTT server.
[1/15/2021, 6:52:19 AM] Connected to volumio player radio-01

**Comment by jti989** [comment]
Hi, just a quick info in between:
the log messages about the server starting up are there, thank you!
I could see that it is indeed hanging in between "Connecting to volumio player" and "Connected to MQTT server".
Now I am struggling to configure mosquitto to have an unencrypted connection in addition to the excrypted.

**Comment by richiewebgate** [comment]
Encrypted connection to MQTT should work as well, although I can't test it right now. To use TLS you must change the connection string in config.js accordingly. I was assuming you want to use an unencrypted port on the mosquitto server (default), because your config.js starts with "mqtt://". For TLS change this to "mqtts://" with the proper port at the end of the connection string. Check https://www.npmjs.com/package/mqtt for further info, maybe you have to extend a few lines to include your own certificates..

**Comment by jti989** [comment]
Yes, encrypted connection may be possible, but my certificate was self signed. So I had no luck with that.
Indeed the logmessages at startup helped me to sort all issues out!
Thank you for you support on this.
