### ISSUE TITLE
PM2 start     status   errored  / AUTOSTART not working 

### ISSUE THREAD

**Issue by swthai** [richiewebgate/volumio-mqtt#16]
volumio@volumioth:~/volumio-mqtt$ pm2 list
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ volumio-mqtt       │ fork     │ 60   │ errored   │ 0%       │ 0b       │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
volumio@volumioth:~/volumio-mqtt$ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/volumio/.pm2/pm2.log last 15 lines:
PM2        | 2022-05-24T22:20:30: PM2 log: App [volumio-mqtt:0] online
PM2        | 2022-05-24T22:20:31: PM2 log: App [volumio-mqtt:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-05-24T22:20:31: PM2 log: App [volumio-mqtt:0] starting in -fork mode-
PM2        | 2022-05-24T22:20:31: PM2 log: App [volumio-mqtt:0] online
PM2        | 2022-05-24T22:20:32: PM2 log: App [volumio-mqtt:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-05-24T22:20:32: PM2 log: App [volumio-mqtt:0] starting in -fork mode-
PM2        | 2022-05-24T22:20:32: PM2 log: App [volumio-mqtt:0] online
PM2        | 2022-05-24T22:20:32: PM2 log: App [volumio-mqtt:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-05-24T22:20:32: PM2 log: App [volumio-mqtt:0] starting in -fork mode-
PM2        | 2022-05-24T22:20:32: PM2 log: App [volumio-mqtt:0] online
PM2        | 2022-05-24T22:20:33: PM2 log: App [volumio-mqtt:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-05-24T22:20:33: PM2 log: App [volumio-mqtt:0] starting in -fork mode-
PM2        | 2022-05-24T22:20:33: PM2 log: App [volumio-mqtt:0] online
PM2        | 2022-05-24T22:20:34: PM2 log: App [volumio-mqtt:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-05-24T22:20:34: PM2 log: Script /home/volumio/volumio-mqtt/server.js had too many unstable restarts (16). Stopped. "errored"

/home/volumio/.pm2/logs/volumio-mqtt-out-0.log last 15 lines:
/home/volumio/.pm2/logs/volumio-mqtt-error-0.log last 15 lines:
0|volumio- | /lib/node_modules/pm2/lib/ProcessContainerFork.js:30
0|volumio- |     import(url.pathToFileURL(process.env.pm_exec_path));
0|volumio- |     ^^^^^^
0|volumio- |
0|volumio- | SyntaxError: Unexpected token import
0|volumio- |     at createScript (vm.js:80:10)
0|volumio- |     at Object.runInThisContext (vm.js:139:10)
0|volumio- |     at Module._compile (module.js:616:28)
0|volumio- |     at Object.Module._extensions..js (module.js:663:10)
0|volumio- |     at Module.load (module.js:565:32)
0|volumio- |     at tryModuleLoad (module.js:505:12)
0|volumio- |     at Function.Module._load (module.js:497:3)
0|volumio- |     at Function.Module.runMain (module.js:693:10)
0|volumio- |     at startup (bootstrap_node.js:188:16)
0|volumio- |     at bootstrap_node.js:609:3

Manual start funktioniert und MQTT läuft stabil.

wenn ich  direkt starte:    node server.js
[2022-5-24 23:08:31] Starting volumio-mqtt
[2022-5-24 23:08:31] Connecting to MQTT server..
[2022-5-24 23:08:32] Connecting to volumio player http://localhost:3000
[2022-5-24 23:08:32] Connected to volumio player volumio01
[2022-5-24 23:08:32] Connected to MQTT server.
[2022-5-24 23:08:32] Connected to MQTT server.
[2022-5-24 23:10:12] Turning outlet OFF
[2022-5-24 23:10:13] Turning outlet OFF

**Comment by richiewebgate** [comment]
Hi! Sounds like a node version issue by PM2. Check [this](https://stackoverflow.com/questions/59834021/pm2-unexpected-token-import) and compare your node version.

**Comment by swthai** [comment]
Hallo, Thank you. working now.
