### ISSUE TITLE
Restarts all the time.

### ISSUE THREAD

**Issue by Bruka** [richiewebgate/volumio-mqtt#4]
status            │ online                                           │
│ name              │ volumio-mqtt                                     │
│ restarts          │ 227                                              │
│ uptime            │ 0s                                               │
│ script path       │ /home/volumio/server.js                          │
│ script args       │ N/A                                              │
│ error log path    │ /home/volumio/.pm2/logs/volumio-mqtt-error-0.log │
│ out log path      │ /home/volumio/.pm2/logs/volumio-mqtt-out-0.log   │
│ pid path          │ /home/volumio/.pm2/pids/volumio-mqtt-0.pid       │
│ interpreter       │ node                                             │
│ interpreter args  │ N/A                                              │
│ script id         │ 0                                                │
│ exec cwd          │ /home/volumio                                    │
│ exec mode         │ fork_mode                                        │
│ node.js version   │ 6.11.0                                           │
│ watch & reload    │ ✘                                                │
│ unstable restarts │ 0                                                │
│ created at        │ 2018-06-21T19:29:46.908Z   

From log:
Error: Cannot find module 'mqtt'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/volumio/server.js:3:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by richiewebgate** [comment]
As the error says.. install the **mqtt** package. It's part of the dependencies in package.json. 
$ npm install
