### ISSUE TITLE
Corrections to readme file

### ISSUE THREAD

**Issue by thomastech** [richiewebgate/volumio-mqtt#8]
I noticed some issues in the readme.
Item 1. set/playPlaylist function is missing (not mentioned).
Item 2. set/addPlaylist} function does not appear to have been implemented.
Item 3. get/browselibrary and status/browselibrary do not appear to have been implemented.

- Thomas

**Comment by richiewebgate** [comment]
thanks for your feedback. I will fix this soon.

**Comment by richiewebgate** [comment]
readme updateds

**Comment by thomastech** [comment]
Thanks!
